### ISSUE TITLE
Hide empty fields

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/modulebuilder#102]
Hide empty fields in generated module template for more clean layout

**Comment by ggoffy** [comment]
IMO this is the choice of module developer, whether he want to show or hide empty fields
e.g. as you wanted in https://github.com/XoopsModules25x/wgdiaries/issues/63 :)

**Comment by mjoelweb** [comment]
I meant something like this<{if $item_notes}>  <{$item_notes}> <{/if}>

:-) but yes maybe we can modify it ourselves in templates

**Comment by ggoffy** [comment]
I know what you meant :) but as I said I think it is freedom of developer and modulebuilder can support us in developing new modules, but do not all :)

btw: use defaults for smarty: `<{if $item_notes|default:''}> <{$item_notes}> <{/if}>`
