### ISSUE TITLE
Missing option to add an image in MyModule sample

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/modulebuilder#107]
There is no field for an image Logo:

![image](https://user-images.githubusercontent.com/613686/122693147-95cfea80-d206-11eb-9b3b-731df9547e4e.png)

but it shows in the list:

![image](https://user-images.githubusercontent.com/613686/122693113-7042e100-d206-11eb-9e2f-6940019953d6.png)

**Comment by ggoffy** [comment]
hi
the sample data are not set properly
![grafik](https://user-images.githubusercontent.com/7547661/123088364-eb361280-d425-11eb-94ba-26bcb85b0c02.png)
there should be a "checked" in "Admin: visible in form"

I will update test data
