### ISSUE TITLE
Hide empty fields 

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/modulebuilder#123]
Hi 

can it be set in default to hide empty fields in files and templates if thats possible

example : the email in copyright
![ss](https://user-images.githubusercontent.com/16532279/142156931-cd73fa16-a825-49b6-9ff9-2ad27d39a8e6.jpg)

for templates: maybe include preference to hide or display fields automatically

**Comment by ggoffy** [comment]
done

https://github.com/XoopsModules25x/modulebuilder/pull/125

**Comment by liomj** [comment]
thank you ggoffy
