### ISSUE TITLE
Blocks - Featured/Spotlight Item

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/modulebuilder#124]
Hi

I would like to suggest a featured/spotlight item block where we can select item prefably using drop down or list box and also define number of item to be featured like a spotlight block (example - the publisher spotlight block)

**Comment by ggoffy** [comment]
hi
the spotlight block of publisher is a very tailormade solution especially for publisher (using cats, display/hide image and so on).

creating a block where you can select one or more specific items should be possible, if this helps

**Comment by liomj** [comment]
> creating a block where you can select one or more specific items should be possible, if this helps

thank you Ggoffy, can you show me if there any existing example i can follow ? im not that good but i can follow example. 

im currently working on a simple staff directory module with modulebuilder where i would like to feature one or two staff in a block

example: featured staff, staff of the month etc

**Comment by ggoffy** [comment]
I will try to implement this feature

btw: do you know https://github.com/XoopsModules25x/wgteams

**Comment by liomj** [comment]
Thanks again ggoffy yes i tried wgteams before last time, and i totally forgot about it, i'll explore it once again, i think it fits my need of a working staff directory..
but still would love to learn and create my own module using modulebuilder,..

keep up the good work on this awesome modulebuilder

**Comment by ggoffy** [comment]
hi liomj

can you please test my last version: https://github.com/ggoffy/modulebuilder

what I have done:
the blocks 'last' 'new' and so on now have only the params for 'number of items' and 'length of title'
![grafik](https://user-images.githubusercontent.com/7547661/143201828-a28f988f-4889-4dec-a81a-d51b766e0b3c.png)
I have removed the select box as it was not working

I have added a new block spotlight
![grafik](https://user-images.githubusercontent.com/7547661/143202070-dbc64852-ad71-4263-9a42-c812d0d96a32.png)
here you have now a select box where you can select one or multiple items
the params for 'number of items' is only used if you select 'all items'

**Comment by liomj** [comment]
Hi ggoffy

 i made some quick test like this

1. Install ggoffy modulebuilder,
- message invalid default value mod_since
- increased the field size to 10 to install the module
- Import sample Data
- build the mymodule sample

3. Install the mymodule module
-change the min_xoops to => 2.5.10 since i use 2.5.11 beta 2
- add categories
Notice: Undefined variable: permissionUpload in file /modules/mymodule/class/Categories.php line 120

- Add new article
- cloned the articles and give it different titles
- Give permission to all articles
- edit blocks/articles.php and change default art_top and art_hits to art_votes
- all blocks display and working


XOOPS Version 	XOOPS 2.5.11-Beta2
PHP Version 	7.4.24
MySQL Version 	5.5.5-10.4.21-MariaDB

**Comment by ggoffy** [comment]
I fixed the problems with field size and permissionUpload 
Thank you for testing
