### ISSUE TITLE
Permission System

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/modulebuilder#126]
Hi it is possible to change the permission using category instead of by item

current example in the sample mymodule, 
![article](https://user-images.githubusercontent.com/16532279/143329624-1c78cf81-336b-4072-b8e5-5b28c587c62e.jpg)

![article2](https://user-images.githubusercontent.com/16532279/143329714-8f3d83fe-b4c5-4d46-ba3c-39b89e9c563e.jpg)
 
just my suggestion maybe we can set the permission when creating the categories instead of in the article form like right now

**Comment by ggoffy** [comment]
Hi 

modulebuilder can do it automatically, if you decide, that you what to apply option permissions for a specific table.
if you what to combine (apply permissions from categories to atricles) then modulebuilder doesn't know when it is creating your module which combinations of permission you expect.

you can do this but you have to do it manually.
- remove option permission from articles
- add option permission to categories 

then you can e.g.
- show only categories in form articles where user have perm to access
- add a check at saving articles whether this is allow for this user or not
and so on. It depends what you need.

**Comment by liomj** [comment]
thank you goffy for the explanation, i tried it works
