### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/modulebuilder#147]
Error: TypeError: htmlspecialchars() expects parameter 1 to be string, int given in file /modules/modulebuilder/class/Form/FormRadio.php line 52

ModuleBuilder 3.6.0 Beta 1 NOT RELEASED (11/04/2021) 
<html><body>

XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.27
MySQL Version | 5.5.5-10.4.22-MariaDB

</body>
</html>

**Comment by ggoffy** [comment]
fixed with https://github.com/XoopsModules25x/modulebuilder/pull/148
