### ISSUE TITLE
 TypeError: mb_strpos() expects parameter 1 to  be string

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/modulebuilder#151]
i tried the import module function and try to update an old custom xoops module of mine, when i tried to build the module, i received this error

the url: http://localhost/xoops/modules/modulebuilder/admin/building.php?op=build&mod_id=4
the error and warning
<html><body>

Warning:   copy(http://localhost/xoops/modules/modulebuilder/assets/images/logos/xoops_logo.png):  failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found  in file /modules/modulebuilder/class/Files/CreateArchitecture.php line  165
--
Error: TypeError: mb_strpos() expects parameter 1 to  be string, null given in file  /modules/modulebuilder/class/Files/CreateFile.php line 343

</body>
</html>

<html><body>

XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.27
MySQL Version | 5.5.5-10.4.22-MariaDB

</body>
</html>

ModuleBuilder 3.6.0 Beta 1 NOT RELEASED (11/04/2021)

**Comment by liomj** [comment]
ok when checking data error before buidling the module, i got some errors for some fields
but i cant rectify the error i still cant access the field edit because of still having this error #150

**Comment by ggoffy** [comment]
please test once more
