### ISSUE TITLE
'tpl_refid_module_set_file_type' unique index is exist. 

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/modulebuilder#159]
Hi i have a backup testdata created with an old version module builder

i tried the latest version of modulebuilder from github with my backup testdata

ModuleBuilder 36 (11/03/2021) 
<html><body>

XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.27
MySQL Version | 5.5.5-10.4.22-MariaDB

</body>
</html>

i received this error when updating the generated module
Array ( [0] => 'tpl_refid_module_set_file_type' unique index is exist. Note: check 'tplfile' table to be sure this index is UNIQUE because XOOPS CORE need it. )

where should i check and fix this ? Thank You

**Comment by ggoffy** [comment]
hi, sorry for late answer. 

only for me to be clear: does the error occur during update of your module, not during update of modulebuilder?

**Comment by liomj** [comment]
Problem occurs when updating My generated module

**Comment by ggoffy** [comment]
can you please send me the module by mail?

**Comment by liomj** [comment]
I've send you an email. Thank you

**Comment by ggoffy** [comment]
I found it:
goto include/update.php and remove lines 34 to 36
this check isn't needed anymore. I will adapt modulebuilder

**Comment by liomj** [comment]
Thank you

**Comment by liomj** [comment]
https://github.com/XoopsModules25x/modulebuilder/pull/160
