### ISSUE TITLE
new xoops_confirm

### ISSUE THREAD

**Issue by ggoffy** [XoopsModules25x/modulebuilder#17]
Currently it is not possible to render xoops confirm and to add it with smarty assign to the template.
To avoid broken template design this should be possible.

Maybe xoops confirm should be modal.

**Comment by ggoffy** [comment]
see also https://github.com/XOOPS/XoopsCore25/issues/560#issuecomment-357804467

**Comment by mambax7** [comment]
Is this a new issue? I'm not aware of any issues in the past with xoops_confirm

What is the use case? Can you describe what is different from the usual cases?

**Comment by ggoffy** [comment]
it was a suggestion from Richard 
https://github.com/XOOPS/XoopsCore25/issues/560#issuecomment-357804467

**Comment by mambax7** [comment]
OK, I see it now. Thanks! 
But in this case, Richard is the one who can provide you with an answer...

**Comment by ggoffy** [comment]
your opinion is also welcome :)

**Comment by geekwright** [comment]
Since the comment you cited, xoops_confirm() now has a theme controlled template - system_confirm.tpl

It still emits HTML, as that is it's well entrenched API.

It is possible to place xoops_confirm() in a template, even though it still generates raw html output. That would look something like this:
```php
     ob_start();
     xoops_confirm(['op'=>'do_action'], '', 'Confirm This', $submit = '', true);
     $output = ob_get_contents();
     ob_end_clean();
     $GLOBALS['xoopsTpl']->assign('confirm_form', $output);
 ```

The problem I see with xoops_confirm() becoming a modal is that the way it is implemented it is very transactional. A tentative transaction is proposed, submitted to be verified, the confirmation displayed, then either the transaction is processed or aborted. The backend php logic gets involved in each step in the xoops_confirm() flow.

A modal confirm that accomplishes the same things as xoops_confirm() is doable, but it would have to do some things differently to allow the transactions to stay in the browser. The tools are all there -- that kind of communication is why Xmf\Jwt exists.

**Comment by ggoffy** [comment]
hi Richard

sorry, I'm dummy programmer ;)
the part from "The problem I see..." is to high for me

What should I implement in Modulebuilder? What should be used? the new xoops_confirm html version?

**Comment by geekwright** [comment]
> sorry, I'm dummy programmer ;)

No, I know better than that ;)

The word "modal" sent me into thinking of implementing xoops_confirm in javascript in browser. Sorry to veer off topic.

I have no problem with alternative ways to implement what xoops_confirm() does. If you see the need for improvements, I believe you.  The existing xoops_confirm() will need to remain, as it is central to many common operations in core and other modules. But new code could be much better off with a more modern implementation!

I've looked at the implementation you presented here:
https://github.com/ggoffy/modulebuilder/commit/856304a725d45e313fc3214de8ff46dd3983f24b

I have some comments, specific to that implementation, that I think could make it stronger.

Let's look at this setup code:
```php
    $xoopsconfirm =  new \XoopsModules\Modulebuilder\Common\XoopsConfirm();
    $xoopsconfirm->hiddens = ['ok' => 1, 'mod_id' => $modId, 'op' => 'delete'];
    $xoopsconfirm->action = \Xmf\Request::getString('REQUEST_URI', '', 'SERVER');
    $xoopsconfirm->object = $modulesObj->getVar('mod_name');
```
This leaves a lot of ways to make a mistake, as it requires 4 statements (or more) that should be only 1.
```php
    $xoopsconfirm =  new \XoopsModules\Modulebuilder\Common\XoopsConfirm(
        ['ok' => 1, 'mod_id' => $modId, 'op' => 'delete'],
        \Xmf\Request::getString('REQUEST_URI', '', 'SERVER'),
        $modulesObj->getVar('mod_name')
    );
```
It looks like $title and $label should be included, too. The public properties should be private (or at least protected,) and all of them passed to and set at once in __construct.

By using the constructor, arguments can be type hinted and the validity of the parameters and resulting form can be determined up front.

Public properties limit how your code can grow. They will always be used by someone, so if you need to make what should be an internal change, external things can be affected. An example in core is class/tree.php where a __get() method was required to keep old code running.

If reading or changing the property outside the constructor is required, it should have getter or setter methods to provide the access.

Also, if it isn't a singleton or a factory, there isn't much reason to have a static getInstance().

With those changes, I think you would be right on the mark. I would want that in core!

**Comment by ggoffy** [comment]
Hi Richard
thanks for compliments :)

I have changed code: https://github.com/ggoffy/modulebuilder/commit/c14394945b642cde0530a4b019f40197cc5a836f

If you agree I will implement this in modulebuilder and all new modules will used this

another question:
do we have additional forms/object similar to xoopsconfirm, which I can implement now?

**Comment by ggoffy** [comment]
implemented
