### ISSUE TITLE
ENUM field wrong generation

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/modulebuilder#24]
This is what I submitted:
`'Left','Center','Right'`
and this is what I've got:
`'&#039;Left&#039;', '&#039;Center&#039;', '&#039;Right&#039;'`

This is the generated SQL code in mysql.sql
`   `image_align`  ENUM ('&#039;Left&#039;', '&#039;Center&#039;', '&#039;Right&#039;') NOT NULL DEFAULT 'Left',`

while it should be:
`    `image_align`  ENUM ('Left','Center','Right') NOT NULL DEFAULT 'Left',`

**Comment by ggoffy** [comment]
fixed
