### ISSUE TITLE
wrong case for varibales

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/modulebuilder#27]
We should remove the `getCamelCase()` or whatever function we're using to generate variables, as sometimes the generated names violate the PSR standards when we have  `$Id` instead of `$id`, or `$Title` instead of `$title`

This was generated in the file /include/comment_functions.php

```
    $rateHandler = $helper->getHandler('Rate');
    $Id          = $comment->getVar('com_itemid');
    $rateObj     = $rateHandler->get($Id);
    $Title       = $rateObj->getVar('title');
```

**Comment by ggoffy** [comment]
Hi Michael

yes, this code in comment_functions.php is bad (and was already corrected with my last commit to ggoffy/modulebuilder ;) )

nevertheless, I would like to clarify:
> $artId = Request::getInt('art_id', 0);

or

> $artId = $articlesObj->getVar('art_id');
> $artTitle = $articlesObj->getVar('art_title');

currently the goal is:
logic from table and field naming: 'art_id' is field in table article, and after underscore we have speaking field name
module_builder is taking the name of table field, remove underscore make uppercase of first character after table identifier. 
therefore we know, if we see the variable $artId, that it contains the content of table article, field art_id

I think this is a good way for naming variables. do you think the same?

**Comment by mambax7** [comment]
That's perfectly OK. 
We just don't want to see variables with capital first letter like `$Title`

**Comment by ggoffy** [comment]
already fixed in latest version
