### ISSUE TITLE
Moduledirname not created

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/modulebuilder#48]
After adding a new module, I tryed to build it (modules/modulebuilder/admin/building.php?op=build&mod_id=1) but I got these messages:

`Error : RuntimeException: Directory "/uploads/modulebuilder/repository/cesagmoduledirname" was not created`

`Warning: mkdir(): No such file or directory in file /modules/modulebuilder/class/Files/CreateStructure.php line 162`

`Error: RuntimeException: Directory "/uploads/modulebuilder/repository/cesagmoduledirname" was not created in file /modules/modulebuilder/class/Files/CreateStructure.php line 163`

___
My config:

PHP 7.4.7
MYSQL 5.7.30-0ubuntu0.16.04.1
XOOPS 2.5.11-Beta1

**Comment by ggoffy** [comment]
hi, cant reproduce it
![grafik](https://user-images.githubusercontent.com/7547661/90000279-3d4bca80-dc90-11ea-96a0-9c44e0ddb775.png)

PHP 7.4.0
Xoops 2.5.11 Beta 1

does upload directory have chmod 0777 ?

**Comment by cesagonchu** [comment]
Yes

**Comment by cesagonchu** [comment]
![image](https://user-images.githubusercontent.com/4613970/90004441-f3fe7980-dc95-11ea-9049-75f88c1d58de.png)

**Comment by ggoffy** [comment]
maybe is the problem, that you haven't defined tables and fields.
can you please add a table with fields and test again

**Comment by cesagonchu** [comment]
![image](https://user-images.githubusercontent.com/4613970/90007050-4fcb0180-dc9a-11ea-9407-6663ace8dc31.png)

same error:

![image](https://user-images.githubusercontent.com/4613970/90007107-6c673980-dc9a-11ea-8402-d25b40116ef3.png)

**Comment by ggoffy** [comment]
can you please export tables to yaml and send me the files by mail?

**Comment by ggoffy** [comment]
fixed problem. an unnecessary mb_strtolower lowered path WEB/xoopsen... into web/xoopsen...
