### ISSUE TITLE
WGGITHUB_XXX

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/modulebuilder#66]
Shouldn't this be "MODULEBUILDER" instead of WGGITHUB in https://github.com/XoopsModules25x/modulebuilder/blob/master/class/Common/XoopsConfirm.php ?

```php
\define('CO__WGGITHUB_DELETE_CONFIRM', 'Confirm delete');
```

**Comment by mambax7** [comment]
Also, is there a reason for the two underscores, instead of one in:

CO__

**Comment by ggoffy** [comment]
solved. thank you
