### ISSUE TITLE
Block Link

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/modulebuilder#69]
There is no link in the blocks of the module created

Generated block example

<{foreach item=service from=$block}>
	<{$service.img}>
	<{$service.title}>
	<{$service.desc}>
<{/foreach}>

Can the link feature to go to content be added?

**Comment by ggoffy** [comment]
implemented
please test

**Comment by Heyula** [comment]
@ggoffy 

Yes it works now.
Thank you.

**Another feature request**

It has the feature of adding single images but the feature of adding multiple images would be much more beautiful.

**Comment by ggoffy** [comment]
I agree, this would be nice. But I implemented multiupload in wgGallery, and this was not an easy/simple job. And to use it like the current upload field we would need to create a xoops form element first.

**Comment by ggoffy** [comment]
hi. I thought a little bit about your idea, but with implementing multiupload you have the problem with storage of data:
if you store data as json in text field, then it is hard to manage it, what info, the path and so on.
if you want to store it file by file in a separate table then you would need a lot of extra params for the field element in modulebuilder/fields
I will close this issue for the moment
