### ISSUE TITLE
PAGE TITLE

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/modulebuilder#72]
Can we add the feature of using article title in page title?

![g1](https://user-images.githubusercontent.com/5504159/105282960-864d6680-5bc0-11eb-96a6-d6ac5ab23338.jpg)

**Comment by ggoffy** [comment]
should be fixed with new version

please test it

**Comment by Heyula** [comment]
Test result is successful.
Thank you.
![1](https://user-images.githubusercontent.com/5504159/106107038-73eea200-6157-11eb-9f3b-292ba5e403d5.jpg)
