### ISSUE TITLE
Article Read Count 

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/modulebuilder#74]
Is it possible to add a feature that indicates how much the article has been read ?

**Comment by ggoffy** [comment]
Hi Eren

can you please test https://github.com/ggoffy/modulebuilder

**Comment by ggoffy** [comment]
please run update of module

**Comment by Heyula** [comment]
Hi ggoffy

Test result is successful.

Thank you so much

![c1](https://user-images.githubusercontent.com/5504159/106236911-d48ce600-620e-11eb-94b4-2336d016ba63.jpg)

**Comment by ggoffy** [comment]
Thank you for the idea and for testing :)
