### ISSUE TITLE
Voting Problem

### ISSUE THREAD

**Issue by Heyula** [XoopsModules25x/modulebuilder#77]
Very nice voting feature.

However, when I vote for the article, it directs me to the module's homepage and does not vote.

![v1](https://user-images.githubusercontent.com/5504159/106293480-1d6c8b00-625f-11eb-9a41-75e5ce5a25d8.jpg)
![v2](https://user-images.githubusercontent.com/5504159/106293484-1e9db800-625f-11eb-8979-02a4040b8863.jpg)

**Comment by ggoffy** [comment]
If I created a module from test data it works without problems. Can you send me your module by mail?

**Comment by Heyula** [comment]
Hi;
I'll create a module again and try.
