### ISSUE TITLE
Editor Preference is the generated module not saved

### ISSUE THREAD

**Issue by mambax7** [XoopsModules25x/modulebuilder#8]
I select TinyMCE and save in Preferences, but I'm still getting DHTML Editor

**Comment by ggoffy** [comment]
current handling:
if you select a field element type "TextArea Field" then it will be always a text area
if you select a field element type "Selectable Editor (Dhtml)" then it use the settings from preferences

make this sense?

**Comment by mambax7** [comment]
Actually, I see that I've made a mistake.  But on the other hand, there is an opportunity for improvement:
As a standard we used to have Editor settings for Admin and for Users. My mistake was that I automatically selected the first (which should be for the Admin), as TinyMCE, and the second (which used to be for the User, as DHTML). 
So when I went to edit the Article, I expected TinyMCE, and I had the DHTML Editor. But I didn't realize that the Editor selection was not for Admni/User, but for Topic/Article.

That doesn't make much sense, because if I select TinyMCE for articles, then the users will also have it, while for security reasons, I might want to give them access to only DHTML.

So I change the label to Enhancement

**Comment by ggoffy** [comment]
I thought also about using editor settings for Admin and for Users. But I think it is better to decide for each input field how to use, because then I can use different editors for different tables, if i want.

**Comment by mambax7** [comment]
Well, **security** should be first, i.e. we should first have a choice between Admin and User, and not between input fields. 
If you want to add these choices in addition to Admin/User, that's OK.

**Comment by ggoffy** [comment]
ok. 
if we have more than one text editor field, and always admin and user, then we are blowing up the preferences to double.
what do you think about following solution:
- on user side you get the editor selected in preferences
- on admin side you have editor with selector to switch to another editor, and editor from preferences preselected

**Comment by mambax7** [comment]
Give me a real life example where would you want different editors, and which ones for which input field?

**Comment by ggoffy** [comment]
maybe in one table I want to add simple description then I can use a simple editor.
in another table I want to add a long text (like an artikel, with different formats, with list,....) then I use TinyMCE

**Comment by ggoffy** [comment]
and i do not understand why I need in admin antoher editor then on user side

**Comment by mambax7** [comment]
Then why don't you set the " simple" field as "textbox" or "textarea" which will prohibit the use of any WYSIWYG editors, and then for those fields that you want to add formatting, you set them as DHTML, which then automatically will use the editor that you selected in Preferences?

**Comment by ggoffy** [comment]
?????

maybe i understand you wrong, but this is what I currently do

**Comment by mambax7** [comment]
So why do you want the selection for a field, if it's already decided which field is allowed to have WYSIWYG formatting?
If you decide which editor you're using, those fields that allow it. will take it from the preferences. One decision point works for all of the fields.

If you want to select an editor individually for, let's say, 4 fields, that's 4 decision points, i.e. too much complexity. 

Think "convention over configuration! :)

**Comment by ggoffy** [comment]
example:
in wgTeams I have the table with the teams, and for team descritpion it maybe it is useful to have TinyMCE or another "exhausted" editor
I can select a field element type "Selectable Editor (Dhtml)" then it use the settings from preferences

for phone number, adress, ... and all the other fields I need only a simple text field, no TinyMCE
I select a field element type "TextArea Field" for these field and then it will be always a text area, and not appear in preferences

**Comment by mambax7** [comment]
Exactly, so why do you need to set the Editor for these fields individually? 
The decision point is: "For all fields which allow WYSIWYG Editor I want to use TinyMCE (or xDHTML)"
So once you set it, XOOPS is smart enough to open the one editor you selected in Preferences. Everything else will be automatically plain text.

**Comment by ggoffy** [comment]
because I want differend editors for these two kinds of field

**Comment by ggoffy** [comment]
"TextArea Field" will be plain text
"Selectable Editor (Dhtml)"  will be selectable

**Comment by mambax7** [comment]
I don't understand it at all. 
When you say: 
> because I want differend editors for these two kinds of field

what fields do you mean? 

Simple fields do NOT use any editor at all!

**Comment by ggoffy** [comment]
"TextArea Field" is a simple field and do not use any editor

**Comment by mambax7** [comment]
Exactly. So why do you need editor selection by field????

Why can't you say: 
- For all fields which allow WYSIWYG Editor I want to use TinyMCE 
- For all text fields there will be no selectable editor, it will be plain text by default

and be done with it?

**Comment by ggoffy** [comment]
Hi Michael
I think you are right: we should keep it simple :)
I went back to single choice

**Comment by mambax7** [comment]
Great! But one for Admins, and one for Users, right? 
![image](https://user-images.githubusercontent.com/613686/82230609-f309b600-98f9-11ea-9f27-201e183cba77.png)

**Comment by ggoffy** [comment]
IMO I do not know what I as admin should use another editor then the others on user side.
But I have not problem with this if you want

**Comment by mambax7** [comment]
Security! For years we didn't give XOOPS Website users access to WYSIWYG editor like TinyMCE, but only DHTML editor or plain text.  
See Point 4 here: https://code.tutsplus.com/tutorials/5-helpful-tips-for-creating-secure-php-applications--net-2260

**Comment by ggoffy** [comment]
ok, will be done.

I am not an expert especially for security reasons, but should xmf/request not filter out these possible security weaknesses? but maybe this is a topic worth to dicuss in general on xoops website, because this is maybe interesting for more users
