### ISSUE TITLE
XoopsFormSelectTheme  for field type 

### ISSUE THREAD

**Issue by JJDai54** [XoopsModules25x/modulebuilder#86]
Hello!
is it possible to add XoopsFormSelectTheme in the type of fields.
I tried, but I'm not sure which files are affected

generated line :
        $sldThemeSelect = new \XoopsFormSelectTheme(_AM_XBOOTSTRAP_SLIDER_THEME, 'sld_theme', $this->getVar('sld_theme'));

**Comment by ggoffy** [comment]
hi

what do you want to achieve?

Only a form select where all themes are listed? or a theme switcher?

for a theme switcher I would recommend the themes block

**Comment by ggoffy** [comment]
can I close this issue?

**Comment by JJDai54** [comment]
J'ai fais la modif de mon côté,
