### ISSUE TITLE
Quote

### ISSUE THREAD

**Issue by JJDai54** [XoopsModules25x/modulebuilder#87]
In the "description" field of the module, if we put a quote, the module generated bug. language files use quotes as delimiters:
bug:
\define('_MI_XBOOTSTRAP_DESC', 'Ce module permet de gérer l'affichage des sliders, Ajout, durée d'affichage, ordre, ...');

correct :
\define('_MI_XBOOTSTRAP_DESC', 'Ce module permet de gérer l\'affichage des sliders, Ajout, durée d\'affichage, ordre, ...');

i use modulebuilder-3.03-A5 on xoops 2.5.10

**Comment by ggoffy** [comment]
I will close this issue, as it is not related to modulebuilder

**Comment by JJDai54** [comment]
ok , j'ai fais la correction, de mon coté, je ne vois pas pourquoi ce n'est pas possible.
