### ISSUE TITLE
CategoriesHandler' not found

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/modulebuilder#94]
![cat](https://user-images.githubusercontent.com/84079049/120318498-826de580-c312-11eb-8750-9ddbd760710e.jpg)

a. in sample data - my module & my module dirty table categories is not selected as default for art_cat field

b. i noticed the table name not changing in element form of table fields if we rename the table eg Categories to Classifications..is this normal ?

after installing the created module we have Categories handler error missing
RuntimeException: Class 'XoopsModules\Mymoduledirty\CategoriesHandler' not found

the module should be using classification handler

ModuleBuilder 3.05 RC1 (11/11/2020)
XOOPS 2.5.11-Beta2
PHP Version 7.4.0
MySQL Version 5.7.28

**Comment by ggoffy** [comment]
> a. in sample data - my module & my module dirty table categories is not selected as default for art_cat field

fixed

**Comment by ggoffy** [comment]
> b. i noticed the table name not changing in element form of table fields if we rename the table eg Categories to Classifications..is this normal ?

yes, you are right. the reason is that the item in the form elements table is only created when the table is created. As the table id is not stored and renaming could have effects on other modules if there the same table name is used (e.g. a table 'categories' is used in two modules). I recommend to create a new table instead of renaming

**Comment by ggoffy** [comment]
> after installing the created module we have Categories handler error missing
> RuntimeException: Class 'XoopsModules\Mymoduledirty\CategoriesHandler' not found

Modulebuilder have also a 'quality check' which you can apply on your data before creating the module (button 'Run data check for errors/inconsistencies before building the module' on tab 'building').
This check shows you if you have some errors or inconsistencies in your design. If you run this check and no error is shown the you will/should get a bug free module :)

I have added 'Mymoduledirty' to test dataset only for demonstration of this tools. Therefore,  'Mymoduledirty' will never run, as it is not properly designed :)

**Comment by mjoelweb** [comment]
thank you goffy
