### ISSUE TITLE
Warning: Use of undefined constant 

### ISSUE THREAD

**Issue by mjoelweb** [XoopsModules25x/modulebuilder#95]
Use sample data - generate module - my Module or my Module Dirty

Warning: Use of undefined constant _AM_MYMODULE_CATEGORIES_LIST - assumed '_AM_MYMODULE_CATEGORIES_LIST' (this will throw an Error in a future version of PHP) in file /modules/mymodule/admin/categories.php line 72

 Warning: Use of undefined constant _AM_MYMODULE_ARTICLES_LIST - assumed '_AM_MYMODULE_ARTICLES_LIST' (this will throw an Error in a future version of PHP) in file /modules/mymodule/admin/articles.php line 72

Warning: Use of undefined constant _AM_MYMODULE_TESTFIELDS_LIST - assumed '_AM_MYMODULE_TESTFIELDS_LIST' (this will throw an Error in a future version of PHP) in file /modules/mymodule/admin/testfields.php line 72

ModuleBuilder 3.05 RC1 (11/11/2020)
XOOPS 2.5.11-Beta2
PHP Version 7.4.0
MySQL Version 5.7.28

**Comment by ggoffy** [comment]
fixed with last version :)

thank you
